### ISSUE TITLE
Building Qt 5.9 instead of 5.8

### ISSUE THREAD

**Issue by Spessi** [Kukkimonsuta/rpi-buildqt#8]
I have compiled Qt 5.9 successfully. The only major thing I had to change was to rename "linux-rpi3-g++" to "linux-rasp-pi3-g++" in the QtBase Build script:
https://github.com/Kukkimonsuta/rpi-buildqt/blob/master/scripts/3.0_build_qtbase.sh#L27 (line 27).
Of course, I also had to change every "5.8" to "5.9" in the script files.

(piomxtextures had errors during the compiliation, but I didn't investigated them any further because I don't need it.)

**Comment by zevero** [comment]
Wow great news. I will try as well!
Did you by any chance compile qtWebEngine? I succeeded with 5.8 albeit mouse interaction did not work, so it was of no use.

**Comment by maitredede** [comment]
I am trying to build qt5.9 with webengine.
Instead of git cloning each module repo, I clone the main qt repo (https://github.com/qt/qt5). It takes some time, but its easy. The 5.9 branch points to branch 5.9.1
I have also applied the fix for the device name.

But I have problems compiling modules : 
- `qtquickcontrols2` : does not find some include files
- `qtmultimedia` : does not find gstreamer

What are the minimum required modules for webengine to work ? And some extension modules ? (for webgl, javascript interaction with qt objects, multimedia, speech) ?

I am compiling with Bash on Ubuntu On Windows (ubuntu 16.04).

**Comment by zevero** [comment]
I succeeded with qtwebengine 5.9 (5.9.1) installing `qtdeclarative qtquickcontrols qtquickcontrols2 qtmultimedia qtsvg qtxmlpatterns qtwebsockets qtserialport qtwebchannel qtwebengine` (`qtdeclarative qtxmlpatterns qtmultimedia qtsvg qtwebchannel` is needed for sure) using a clean Raspbian Lite on Debian (had to add `sudo apt-get instlall gperf, bison, flex, gcc-mulitlib, g++ mulitlib, libx32gcc-4.8-dev`) additionally to the hints on my fork  https://github.com/zevero/rpi-buildqt (get rid of "-r" of qmake ... it is not needed)

However I still have no mouse interaction and on 5.9 the browser is sometimes behaving weird (loading a webpage until 90% - but not finishing for a long time. Or finishing and reloading and stalling at 70% - although the whole webpage is responsive...)

**Comment by Kukkimonsuta** [comment]
In the following week I'll try to update the scripts to be able to build both `5.8` and `5.9` branches. No promises on `webengine` though.

**Comment by Kukkimonsuta** [comment]
Scripts on `dev` branch should now be building both `5.8` and `5.9` variantions
